#!/bin/bash
# Quick command reference

echo "🚀 Tyche Development Commands"
echo "============================"
echo ""
echo "📝 Daily Work:"
echo "  just work <issue-num>    - Work on existing issue"
echo "  just feature <name>      - Create & start new feature"
echo "  just fix <name>          - Create & start bugfix"
echo "  git commit -m 'message'  - Simple commits (hooks run automatically)"
echo "  just pr                  - Create pull request"
echo "  just check               - Run all checks"
echo ""
echo "📊 Status:"
echo "  just status              - Current branch & changes"
echo "  just context             - Show current task"
echo "  gh issue list            - Open issues"
echo "  just report              - Weekly summary"
echo ""
echo "🔧 Utilities:"
echo "  npm run check:fix        - Fix lint/format issues"
echo "  npm test -- --watch      - Test watch mode"
echo "  just refresh-context     - Update task context"
echo "" 